#!/usr/bin/env python3
"""Compute hypothesis-oriented metrics for DDGP local solution counts.

This script is deliberately exploratory. It augments the exact local counts
with graph-theoretic and bitset metrics that can be used to test candidate
theories for the number of local solutions. The strongest current test uses
mirror-compatible graph masks generated by dependency cones and base-clique
closures.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
from collections import deque
from pathlib import Path
from typing import Iterable

from ddgp_count_solutions import (
    Edge,
    Instance,
    Point,
    dist,
    edge,
    intersection_candidates,
    load_instance,
)


Mask = tuple[int, ...]
GraphGenerator = tuple[Mask, tuple[int, ...], str]


def format_vertices(vertices: Iterable[int]) -> str:
    return "{" + ",".join(str(v + 1) for v in sorted(vertices)) + "}"


def format_mask(mask: Mask, decisions: tuple[int, ...]) -> str:
    return "{" + ",".join(str(v + 1) for bit, v in zip(mask, decisions) if bit) + "}"


def format_generator(generator: GraphGenerator, decisions: tuple[int, ...]) -> str:
    mask, mirror, kind = generator
    mirror_text = "{" + ",".join(str(v + 1) for v in mirror) + "}"
    return f"{format_mask(mask, decisions)}@{mirror_text}:{kind}"


def log2_int(value: int) -> int | None:
    if value <= 0:
        return None
    exponent = int(math.log2(value))
    return exponent if 2**exponent == value else None


def constraints_by_target(edges: Iterable[Edge]) -> dict[int, list[Edge]]:
    by_target: dict[int, list[Edge]] = {}
    for u, v in edges:
        by_target.setdefault(v, []).append((u, v))
    return by_target


def enumerate_bit_realizations(
    instance: Instance,
    active_edges: Iterable[Edge],
    vertices: set[int],
    tol: float,
) -> set[tuple[int, ...]]:
    """Enumerate local solutions and return their branch bitstrings.

    Bits are recorded only for non-seed vertices in ``vertices``. Candidate
    order follows ``circle_intersections`` and is used as a local coding device;
    the script tests whether this coding supports the proposed cone symmetries.
    """

    active_constraints = set(active_edges) - set(instance.discretization_edges)
    active_constraints = {e for e in active_constraints if e[0] in vertices and e[1] in vertices}
    by_target = constraints_by_target(active_constraints)
    search_vertices = tuple(i for i in range(instance.k + 1, instance.n) if i in vertices)
    decision_index = {vertex: idx for idx, vertex in enumerate(search_vertices)}

    coords: list[Point | None] = [None] * instance.n
    for i in range(instance.k + 1):
        coords[i] = instance.points[i]

    bits = [0] * len(search_vertices)
    realized: set[tuple[int, ...]] = set()

    def search(position: int) -> None:
        if position == len(search_vertices):
            realized.add(tuple(bits))
            return

        i = search_vertices[position]
        predecessors = instance.predecessor_sets[i]
        if any(predecessor not in vertices for predecessor in predecessors):
            raise ValueError(f"Vertex {i + 1} has a predecessor outside the induced vertex set.")
        centers = tuple(coords[predecessor] for predecessor in predecessors)
        assert all(center is not None for center in centers)

        candidates = intersection_candidates(
            centers,  # type: ignore[arg-type]
            tuple(instance.distances[edge(predecessor, i)] for predecessor in predecessors),
        )

        for bit, candidate in enumerate(candidates):
            coords[i] = candidate
            bits[decision_index[i]] = bit
            feasible = True
            for u, v in by_target.get(i, []):
                assert v == i
                assert coords[u] is not None
                if abs(dist(coords[u], candidate) - instance.distances[(u, v)]) > tol:
                    feasible = False
                    break
            if feasible:
                search(position + 1)
            coords[i] = None
            bits[decision_index[i]] = 0

    search(0)
    return realized


def dependency_sets(instance: Instance) -> list[set[int]]:
    fix_sets = [set([i]) for i in range(instance.n)]
    for i in range(instance.k + 1, instance.n):
        fixed = {i}
        for u in instance.predecessor_sets[i]:
            fixed |= fix_sets[u]
        fix_sets[i] = fixed
    return fix_sets


def dependency_children(instance: Instance) -> dict[int, list[int]]:
    children = {i: [] for i in range(instance.n)}
    for child, predecessors in instance.predecessor_sets.items():
        if child <= instance.k:
            continue
        for parent in predecessors:
            children[parent].append(child)
    return children


def descendants(children: dict[int, list[int]], source: int) -> set[int]:
    reached = {source}
    stack = [source]
    while stack:
        vertex = stack.pop()
        for child in children[vertex]:
            if child not in reached:
                reached.add(child)
                stack.append(child)
    return reached


def xor_mask(bits: tuple[int, ...], mask: Mask) -> tuple[int, ...]:
    return tuple(bit ^ toggle for bit, toggle in zip(bits, mask))


def mask_preserves(bitset: set[tuple[int, ...]], mask: Mask) -> bool:
    return all(xor_mask(bits, mask) in bitset for bits in bitset)


def gf2_rank(masks: Iterable[Mask]) -> int:
    rows = []
    for mask in masks:
        value = 0
        for idx, bit in enumerate(mask):
            if bit:
                value |= 1 << idx
        if value:
            rows.append(value)

    rank = 0
    while rows:
        pivot = max(rows)
        rows.remove(pivot)
        rank += 1
        pivot_bit = pivot.bit_length() - 1
        rows = [row ^ pivot if row & (1 << pivot_bit) else row for row in rows]
        rows = [row for row in rows if row]
    return rank


def span_elements(masks: Iterable[Mask], width: int | None = None) -> set[Mask]:
    basis: list[int] = []
    span_width = 0 if width is None else width
    for mask in masks:
        span_width = max(span_width, len(mask))
        value = 0
        for idx, bit in enumerate(mask):
            if bit:
                value |= 1 << idx
        if not value:
            continue

        candidate = value
        for pivot in basis:
            candidate = min(candidate, candidate ^ pivot)
        if candidate:
            pivot_bit = candidate.bit_length() - 1
            basis = [row ^ candidate if row & (1 << pivot_bit) else row for row in basis]
            basis.append(candidate)
            basis.sort(reverse=True)

    values = {0}
    for pivot in basis:
        values |= {value ^ pivot for value in list(values)}

    return {
        tuple((value >> idx) & 1 for idx in range(span_width))
        for value in values
    }


def masks_in_span(masks: Iterable[Mask], generators: Iterable[Mask]) -> bool:
    mask_list = list(masks)
    generator_list = list(generators)
    width = max((len(mask) for mask in mask_list + generator_list), default=0)
    generator_span = span_elements(generator_list, width=width)
    return all(mask in generator_span for mask in mask_list)


def all_masks(width: int) -> list[Mask]:
    masks = []
    for value in range(2**width):
        masks.append(tuple((value >> idx) & 1 for idx in range(width)))
    return masks


def translation_stabilizer(bitset: set[tuple[int, ...]], width: int) -> list[Mask]:
    return [mask for mask in all_masks(width) if mask_preserves(bitset, mask)]


def affine_hull_rank(bitset: set[tuple[int, ...]]) -> int:
    if not bitset:
        return 0
    origin = next(iter(bitset))
    differences = []
    for bits in bitset:
        differences.append(tuple(a ^ b for a, b in zip(origin, bits)))
    return gf2_rank(differences)


def is_affine_subspace(bitset: set[tuple[int, ...]]) -> bool:
    if not bitset:
        return False
    return len(bitset) == 2 ** affine_hull_rank(bitset)


def orbit_count(bitset: set[tuple[int, ...]], masks: list[Mask]) -> tuple[int, int]:
    if not bitset:
        return 0, 0

    unseen = set(bitset)
    count = 0
    largest = 0
    while unseen:
        count += 1
        start = unseen.pop()
        orbit = {start}
        queue: deque[tuple[int, ...]] = deque([start])
        while queue:
            bits = queue.popleft()
            for mask in masks:
                nxt = xor_mask(bits, mask)
                if nxt in bitset and nxt not in orbit:
                    orbit.add(nxt)
                    queue.append(nxt)
                    unseen.discard(nxt)
        largest = max(largest, len(orbit))
    return count, largest


def base_clique_metrics(instance: Instance, local_vertices: set[int]) -> dict[str, int]:
    nodes: dict[tuple[int, ...], list[int]] = {}
    for child in range(instance.k + 1, instance.n):
        clique = tuple(sorted(instance.predecessor_sets[child]))
        nodes.setdefault(clique, []).append(child)

    child_to_base = {child: clique for clique, children in nodes.items() for child in children}
    transitions: set[tuple[tuple[int, ...], tuple[int, ...]]] = set()
    for target in nodes:
        for vertex in target:
            source = child_to_base.get(vertex)
            if source is not None and source != target:
                transitions.add((source, target))

    overlap_edges: set[tuple[tuple[int, ...], tuple[int, ...]]] = set()
    node_list = sorted(nodes)
    for idx, left in enumerate(node_list):
        for right in node_list[idx + 1 :]:
            shared = len(set(left) & set(right))
            if shared >= instance.k - 1 and shared > 0:
                overlap_edges.add((left, right))

    local_nodes = {clique for clique in nodes if set(clique) <= local_vertices}
    local_transitions = {(a, b) for a, b in transitions if a in local_nodes and b in local_nodes}
    local_overlaps = {(a, b) for a, b in overlap_edges if a in local_nodes and b in local_nodes}

    adjacency = {clique: [] for clique in local_nodes}
    for source, target in local_transitions:
        adjacency[source].append(target)

    path_count = 0
    max_path_length = 0
    for source in local_nodes:
        queue = deque([(source, 0)])
        while queue:
            current, length = queue.popleft()
            for target in adjacency[current]:
                next_length = length + 1
                path_count += 1
                max_path_length = max(max_path_length, next_length)
                queue.append((target, next_length))

    return {
        "base_cliques": len(nodes),
        "base_clique_transitions": len(transitions),
        "base_clique_overlaps": len(overlap_edges),
        "local_base_cliques": len(local_nodes),
        "local_base_clique_transitions": len(local_transitions),
        "local_base_clique_overlaps": len(local_overlaps),
        "local_base_clique_paths": path_count,
        "local_base_clique_max_path": max_path_length,
    }


def base_clique_closure_masks(
    instance: Instance,
    children: dict[int, list[int]],
    local_vertices: set[int],
    decisions: tuple[int, ...],
) -> list[tuple[int, ...]]:
    decision_set = set(decisions)
    generated_by_clique: dict[tuple[int, ...], set[int]] = {}
    for child in range(instance.k + 1, instance.n):
        if child not in local_vertices:
            continue
        clique = tuple(sorted(instance.predecessor_sets[child]))
        if set(clique) <= local_vertices:
            generated_by_clique.setdefault(clique, set()).add(child)

    masks = []
    for generated_vertices in generated_by_clique.values():
        support: set[int] = set()
        for vertex in generated_vertices:
            support |= descendants(children, vertex) & decision_set
        mask = tuple(1 if vertex in support else 0 for vertex in decisions)
        if any(mask):
            masks.append(mask)
    return sorted(set(masks))


def graph_generators(
    instance: Instance,
    children: dict[int, list[int]],
    local_vertices: set[int],
    decisions: tuple[int, ...],
) -> list[GraphGenerator]:
    decision_set = set(decisions)
    generators: list[GraphGenerator] = []

    for source in decisions:
        support = descendants(children, source) & decision_set
        mask = tuple(1 if vertex in support else 0 for vertex in decisions)
        mirror = tuple(sorted(instance.predecessor_sets[source]))
        if any(mask):
            generators.append((mask, mirror, "cone"))

    generated_by_clique: dict[tuple[int, ...], set[int]] = {}
    for child in range(instance.k + 1, instance.n):
        if child not in local_vertices:
            continue
        clique = tuple(sorted(instance.predecessor_sets[child]))
        if set(clique) <= local_vertices:
            generated_by_clique.setdefault(clique, set()).add(child)

    for clique, generated_vertices in generated_by_clique.items():
        support: set[int] = set()
        for vertex in generated_vertices:
            support |= descendants(children, vertex) & decision_set
        mask = tuple(1 if vertex in support else 0 for vertex in decisions)
        if any(mask):
            generators.append((mask, clique, "base-clique"))

    return sorted(set(generators), key=lambda item: (item[0], item[1], item[2]))


def mirror_rule_preserves_pruning(generator: GraphGenerator, pruning_edge: Edge, decisions: tuple[int, ...]) -> bool:
    mask, mirror, _ = generator
    support = {vertex for bit, vertex in zip(mask, decisions) if bit}
    mirror_set = set(mirror)
    u, v = pruning_edge
    u_in_support = u in support
    v_in_support = v in support

    if u_in_support == v_in_support:
        return True
    fixed_endpoint = v if u_in_support else u
    return fixed_endpoint in mirror_set


def mirror_rule_preserves_edges(
    generator: GraphGenerator,
    edges: Iterable[Edge],
    decisions: tuple[int, ...],
) -> bool:
    mask, mirror, _ = generator
    support = {vertex for bit, vertex in zip(mask, decisions) if bit}
    mirror_set = set(mirror)
    for u, v in edges:
        u_in_support = u in support
        v_in_support = v in support
        if u_in_support == v_in_support:
            continue
        fixed_endpoint = v if u_in_support else u
        if fixed_endpoint not in mirror_set:
            return False
    return True


def generator_violation_signature(
    generator: GraphGenerator,
    edges: Iterable[Edge],
    decisions: tuple[int, ...],
) -> Mask:
    return tuple(
        0 if mirror_rule_preserves_edges(generator, {edge}, decisions) else 1
        for edge in sorted(edges)
    )


def violation_kernel_masks(
    generators: Iterable[GraphGenerator],
    edges: Iterable[Edge],
    decisions: tuple[int, ...],
) -> list[Mask]:
    edge_list = tuple(sorted(edges))
    decision_count = len(decisions)
    combined_vectors = [
        generator[0] + generator_violation_signature(generator, edge_list, decisions)
        for generator in generators
    ]
    combined_span = span_elements(
        combined_vectors,
        width=decision_count + len(edge_list),
    )
    return sorted(
        {
            vector[:decision_count]
            for vector in combined_span
            if not any(vector[decision_count:])
        }
    )


def violation_kernel_rank(
    generators: Iterable[GraphGenerator],
    edges: Iterable[Edge],
    decisions: tuple[int, ...],
) -> int:
    edge_list = tuple(sorted(edges))
    decision_count = len(decisions)
    combined_vectors = [
        generator[0] + generator_violation_signature(generator, edge_list, decisions)
        for generator in generators
    ]
    violation_vectors = [vector[decision_count:] for vector in combined_vectors]
    return gf2_rank(combined_vectors) - gf2_rank(violation_vectors)


def labelled_violation_vectors(
    generators: Iterable[GraphGenerator],
    edges: Iterable[Edge],
    decisions: tuple[int, ...],
) -> tuple[list[Mask], tuple[tuple[Edge, tuple[int, ...]], ...]]:
    generator_list = list(generators)
    labels = tuple(
        sorted(
            {
                (edge, generator[1])
                for generator in generator_list
                for edge in edges
                if not mirror_rule_preserves_edges(generator, {edge}, decisions)
            }
        )
    )
    label_index = {label: idx for idx, label in enumerate(labels)}

    vectors = []
    for generator in generator_list:
        violation = [0] * len(labels)
        for edge in edges:
            label = (edge, generator[1])
            if label in label_index and not mirror_rule_preserves_edges(generator, {edge}, decisions):
                violation[label_index[label]] = 1
        vectors.append(tuple(violation))
    return vectors, labels


def labelled_violation_kernel_rank(
    generators: Iterable[GraphGenerator],
    edges: Iterable[Edge],
    decisions: tuple[int, ...],
) -> int:
    generator_list = list(generators)
    violation_vectors, _ = labelled_violation_vectors(generator_list, edges, decisions)
    combined_vectors = [
        generator[0] + violation
        for generator, violation in zip(generator_list, violation_vectors)
    ]
    return gf2_rank(combined_vectors) - gf2_rank(violation_vectors)


def labelled_violation_kernel_masks(
    generators: Iterable[GraphGenerator],
    edges: Iterable[Edge],
    decisions: tuple[int, ...],
) -> list[Mask]:
    generator_list = list(generators)
    decision_count = len(decisions)
    violation_vectors, labels = labelled_violation_vectors(generator_list, edges, decisions)
    combined_vectors = [
        generator[0] + violation
        for generator, violation in zip(generator_list, violation_vectors)
    ]

    combined_span = span_elements(
        combined_vectors,
        width=decision_count + len(labels),
    )
    return sorted(
        {
            vector[:decision_count]
            for vector in combined_span
            if not any(vector[decision_count:])
        }
    )


def hypothesis_row(instance: Instance, count_row: dict[str, str], tol: float) -> dict[str, object]:
    fix_sets = dependency_sets(instance)
    u, v = instance.pruning_edge
    local_vertices = fix_sets[u] | fix_sets[v]
    local_base_edges = {e for e in instance.base_edges if e[0] in local_vertices and e[1] in local_vertices}
    local_valid_edges = local_base_edges | {instance.pruning_edge}

    decisions = tuple(i for i in range(instance.k + 1, instance.n) if i in local_vertices)
    decision_set = set(decisions)
    base_bits = enumerate_bit_realizations(instance, local_base_edges, local_vertices, tol)
    valid_bits = enumerate_bit_realizations(instance, local_valid_edges, local_vertices, tol)

    children = dependency_children(instance)
    endpoint_set = set(instance.pruning_edge)
    cone_masks: list[tuple[int, ...]] = []
    separating_masks: list[tuple[int, ...]] = []
    for source in decisions:
        cone = descendants(children, source) & decision_set
        mask = tuple(1 if vertex in cone else 0 for vertex in decisions)
        cone_masks.append(mask)
        full_cone = descendants(children, source)
        if len(endpoint_set & full_cone) == 1:
            separating_masks.append(mask)

    base_allowed_masks = [mask for mask in cone_masks if mask_preserves(base_bits, mask)]
    valid_preserving_masks = [mask for mask in base_allowed_masks if mask_preserves(valid_bits, mask)]
    clique_closure_masks = base_clique_closure_masks(instance, children, local_vertices, decisions)
    graph_generator_records = graph_generators(instance, children, local_vertices, decisions)
    graph_generator_masks = sorted({generator[0] for generator in graph_generator_records})
    graph_base_generator_masks = [
        mask for mask in graph_generator_masks if mask_preserves(base_bits, mask)
    ]
    graph_base_generator_records = [
        generator for generator in graph_generator_records if mask_preserves(base_bits, generator[0])
    ]
    edge_rule_base_generator_records = [
        generator
        for generator in graph_generator_records
        if mirror_rule_preserves_edges(generator, local_base_edges, decisions)
    ]
    edge_rule_base_generator_masks = sorted({generator[0] for generator in edge_rule_base_generator_records})
    mirror_rule_generator_records = [
        generator
        for generator in graph_base_generator_records
        if mirror_rule_preserves_pruning(generator, instance.pruning_edge, decisions)
    ]
    mirror_rule_generator_masks = sorted({generator[0] for generator in mirror_rule_generator_records})
    mirror_rule_span = span_elements(mirror_rule_generator_masks, width=len(decisions))
    edge_rule_mirror_generator_records = [
        generator
        for generator in edge_rule_base_generator_records
        if mirror_rule_preserves_pruning(generator, instance.pruning_edge, decisions)
    ]
    edge_rule_mirror_generator_masks = sorted(
        {generator[0] for generator in edge_rule_mirror_generator_records}
    )
    edge_rule_mirror_span = span_elements(edge_rule_mirror_generator_masks, width=len(decisions))
    graph_base_span = span_elements(graph_base_generator_masks, width=len(decisions))
    graph_valid_span_stabilizer = [
        mask for mask in graph_base_span if mask_preserves(valid_bits, mask)
    ]
    separating_allowed_masks = [
        mask for mask in separating_masks if mask_preserves(base_bits, mask)
    ]
    separating_killed_masks = [
        mask
        for mask in separating_allowed_masks
        if not mask_preserves(valid_bits, mask)
    ]

    base_allowed_rank = gf2_rank(base_allowed_masks)
    valid_preserving_rank = gf2_rank(valid_preserving_masks)
    clique_closure_rank = gf2_rank(clique_closure_masks)
    graph_base_generator_rank = gf2_rank(graph_base_generator_masks)
    edge_rule_base_generator_rank = gf2_rank(edge_rule_base_generator_masks)
    graph_valid_span_stabilizer_rank = gf2_rank(graph_valid_span_stabilizer)
    mirror_rule_generator_rank = gf2_rank(mirror_rule_generator_masks)
    edge_rule_mirror_generator_rank = gf2_rank(edge_rule_mirror_generator_masks)
    separating_allowed_rank = gf2_rank(separating_allowed_masks)
    separating_killed_rank = gf2_rank(separating_killed_masks)

    local_base_count = int(count_row["local_base_count"])
    local_valid_count = int(count_row["local_valid_count"])
    local_base_dim = log2_int(local_base_count)
    local_valid_dim = log2_int(local_valid_count)
    full_base_stabilizer = translation_stabilizer(base_bits, len(decisions))
    full_valid_stabilizer = translation_stabilizer(valid_bits, len(decisions))
    full_base_stabilizer_rank = gf2_rank(full_base_stabilizer)
    full_valid_stabilizer_rank = gf2_rank(full_valid_stabilizer)

    predicted_by_killed_rank = (
        local_base_count // (2**separating_killed_rank)
        if local_base_count % (2**separating_killed_rank) == 0
        else None
    )
    predicted_by_allowed_rank = (
        local_base_count // (2**separating_allowed_rank)
        if local_base_count % (2**separating_allowed_rank) == 0
        else None
    )
    predicted_by_valid_rank = 2**valid_preserving_rank
    predicted_by_full_valid_rank = 2**full_valid_stabilizer_rank
    predicted_by_graph_valid_span = 2**graph_valid_span_stabilizer_rank
    predicted_by_mirror_rule = 2**mirror_rule_generator_rank
    predicted_by_edge_rule_mirror = 2**edge_rule_mirror_generator_rank

    base_orbits, base_largest_orbit = orbit_count(base_bits, base_allowed_masks)
    valid_orbits, valid_largest_orbit = orbit_count(valid_bits, valid_preserving_masks)
    full_valid_orbits, full_valid_largest_orbit = orbit_count(valid_bits, full_valid_stabilizer)

    row: dict[str, object] = {
        "id": instance.instance_id,
        "pruning_kind": instance.pruning_kind,
        "pruning_edge": f"{u + 1}-{v + 1}",
        "local_decisions": len(decisions),
        "local_base_count": local_base_count,
        "local_valid_count": local_valid_count,
        "local_base_dim": "" if local_base_dim is None else local_base_dim,
        "local_valid_dim": "" if local_valid_dim is None else local_valid_dim,
        "removed_dim": ""
        if local_base_dim is None or local_valid_dim is None
        else local_base_dim - local_valid_dim,
        "cone_mask_count": len(cone_masks),
        "base_allowed_cone_count": len(base_allowed_masks),
        "base_allowed_cone_rank": base_allowed_rank,
        "valid_preserving_cone_count": len(valid_preserving_masks),
        "valid_preserving_cone_rank": valid_preserving_rank,
        "base_clique_closure_mask_count": len(clique_closure_masks),
        "base_clique_closure_mask_rank": clique_closure_rank,
        "graph_base_generator_count": len(graph_base_generator_masks),
        "graph_base_generator_rank": graph_base_generator_rank,
        "edge_rule_base_generator_count": len(edge_rule_base_generator_masks),
        "edge_rule_base_generator_rank": edge_rule_base_generator_rank,
        "graph_valid_span_stabilizer_count": len(graph_valid_span_stabilizer),
        "graph_valid_span_stabilizer_rank": graph_valid_span_stabilizer_rank,
        "mirror_rule_generator_count": len(mirror_rule_generator_masks),
        "mirror_rule_generator_rank": mirror_rule_generator_rank,
        "edge_rule_mirror_generator_count": len(edge_rule_mirror_generator_masks),
        "edge_rule_mirror_generator_rank": edge_rule_mirror_generator_rank,
        "full_base_stabilizer_count": len(full_base_stabilizer),
        "full_base_stabilizer_rank": full_base_stabilizer_rank,
        "full_valid_stabilizer_count": len(full_valid_stabilizer),
        "full_valid_stabilizer_rank": full_valid_stabilizer_rank,
        "separating_cone_count": len(separating_masks),
        "separating_allowed_cone_count": len(separating_allowed_masks),
        "separating_allowed_cone_rank": separating_allowed_rank,
        "separating_killed_cone_count": len(separating_killed_masks),
        "separating_killed_cone_rank": separating_killed_rank,
        "predicted_valid_by_killed_rank": ""
        if predicted_by_killed_rank is None
        else predicted_by_killed_rank,
        "predicted_valid_by_allowed_rank": ""
        if predicted_by_allowed_rank is None
        else predicted_by_allowed_rank,
        "predicted_valid_by_valid_rank": predicted_by_valid_rank,
        "predicted_valid_by_full_valid_rank": predicted_by_full_valid_rank,
        "predicted_valid_by_graph_valid_span": predicted_by_graph_valid_span,
        "predicted_valid_by_mirror_rule": predicted_by_mirror_rule,
        "predicted_valid_by_edge_rule_mirror": predicted_by_edge_rule_mirror,
        "h2_killed_rank_matches": predicted_by_killed_rank == local_valid_count,
        "h2_allowed_rank_matches": predicted_by_allowed_rank == local_valid_count,
        "valid_rank_matches": predicted_by_valid_rank == local_valid_count,
        "graph_valid_span_rank_matches": predicted_by_graph_valid_span == local_valid_count,
        "mirror_rule_rank_matches": predicted_by_mirror_rule == local_valid_count,
        "edge_rule_mirror_rank_matches": predicted_by_edge_rule_mirror == local_valid_count,
        "full_valid_rank_matches": predicted_by_full_valid_rank == local_valid_count,
        "full_base_stabilizer_in_graph_span": masks_in_span(
            full_base_stabilizer,
            graph_base_generator_masks,
        ),
        "full_valid_stabilizer_in_graph_span": masks_in_span(
            full_valid_stabilizer,
            graph_base_generator_masks,
        ),
        "graph_base_rank_matches_full_base": graph_base_generator_rank == full_base_stabilizer_rank,
        "edge_rule_base_rank_matches_full_base": edge_rule_base_generator_rank
        == full_base_stabilizer_rank,
        "full_base_stabilizer_in_edge_rule_span": masks_in_span(
            full_base_stabilizer,
            edge_rule_base_generator_masks,
        ),
        "graph_valid_rank_matches_full_valid": graph_valid_span_stabilizer_rank
        == full_valid_stabilizer_rank,
        "full_valid_stabilizer_in_mirror_rule_span": masks_in_span(
            full_valid_stabilizer,
            mirror_rule_generator_masks,
        ),
        "mirror_rule_rank_matches_full_valid": mirror_rule_generator_rank
        == full_valid_stabilizer_rank,
        "edge_rule_mirror_rank_matches_full_valid": edge_rule_mirror_generator_rank
        == full_valid_stabilizer_rank,
        "full_valid_stabilizer_in_edge_rule_mirror_span": masks_in_span(
            full_valid_stabilizer,
            edge_rule_mirror_generator_masks,
        ),
        "base_orbits_under_allowed_cones": base_orbits,
        "base_largest_orbit_under_allowed_cones": base_largest_orbit,
        "valid_orbits_under_preserving_cones": valid_orbits,
        "valid_largest_orbit_under_preserving_cones": valid_largest_orbit,
        "full_valid_orbits_under_stabilizer": full_valid_orbits,
        "full_valid_largest_orbit_under_stabilizer": full_valid_largest_orbit,
        "base_single_orbit": base_orbits == 1,
        "valid_single_orbit": valid_orbits == 1,
        "full_valid_single_orbit": full_valid_orbits == 1,
        "base_is_affine_subspace": is_affine_subspace(base_bits),
        "valid_is_affine_subspace": is_affine_subspace(valid_bits),
        "base_affine_hull_rank": affine_hull_rank(base_bits),
        "valid_affine_hull_rank": affine_hull_rank(valid_bits),
        "decisions": format_vertices(decisions),
        "base_allowed_cones": ";".join(format_mask(mask, decisions) for mask in base_allowed_masks),
        "valid_preserving_cones": ";".join(format_mask(mask, decisions) for mask in valid_preserving_masks),
        "base_clique_closure_masks": ";".join(format_mask(mask, decisions) for mask in clique_closure_masks),
        "graph_base_generators": ";".join(format_mask(mask, decisions) for mask in graph_base_generator_masks),
        "edge_rule_base_generators": ";".join(
            format_generator(generator, decisions) for generator in edge_rule_base_generator_records
        ),
        "graph_valid_span_stabilizer_masks": ";".join(format_mask(mask, decisions) for mask in graph_valid_span_stabilizer),
        "mirror_rule_generators": ";".join(
            format_generator(generator, decisions) for generator in mirror_rule_generator_records
        ),
        "mirror_rule_span_masks": ";".join(format_mask(mask, decisions) for mask in sorted(mirror_rule_span)),
        "edge_rule_mirror_generators": ";".join(
            format_generator(generator, decisions) for generator in edge_rule_mirror_generator_records
        ),
        "edge_rule_mirror_span_masks": ";".join(
            format_mask(mask, decisions) for mask in sorted(edge_rule_mirror_span)
        ),
        "full_valid_stabilizer_masks": ";".join(format_mask(mask, decisions) for mask in full_valid_stabilizer),
        "separating_allowed_cones": ";".join(format_mask(mask, decisions) for mask in separating_allowed_masks),
        "separating_killed_cones": ";".join(format_mask(mask, decisions) for mask in separating_killed_masks),
    }
    row.update(base_clique_metrics(instance, local_vertices))
    return row


def load_counts(path: Path) -> dict[str, dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as fh:
        return {row["id"]: row for row in csv.DictReader(fh)}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--instances", type=Path, default=Path("experiments/single-pruning/instances.jsonl"))
    parser.add_argument("--counts", type=Path, default=Path("experiments/single-pruning/counts.csv"))
    parser.add_argument("--out", type=Path, default=Path("research/hypothesis-metrics.csv"))
    parser.add_argument("--tol", type=float, default=1e-5)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    counts_by_id = load_counts(args.counts)
    rows = []
    with args.instances.open(encoding="utf-8") as fh:
        for line in fh:
            if not line.strip():
                continue
            instance = load_instance(json.loads(line))
            rows.append(hypothesis_row(instance, counts_by_id[instance.instance_id], args.tol))

    if not rows:
        raise RuntimeError(f"No instances found in {args.instances}.")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    with args.out.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)

    print(f"wrote {len(rows)} row(s) to {args.out}")


if __name__ == "__main__":
    main()
